FROM python:3.12-slim

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

COPY start-api.sh /start-api.sh
RUN chmod +x /start-api.sh

CMD ["/start-api.sh"]


# FROM python:3.12-slim

# WORKDIR /app
# COPY . .

# RUN pip install --no-cache-dir -r requirements.txt

# EXPOSE 8080


# COPY start-api.sh /start-api.sh
# RUN chmod +x /start-api.sh

# CMD ["/start-api.sh"]
# # CMD ["python", "-m", "uvicorn", "app.modules.qr_generator.backend.main:app", "--host", "0.0.0.0", "--port", "8080"]
